##################################################################
## Holiday Automations
##################################################################

        ##########################################################
        ## Enable Christmas Lighting
        ##########################################################

- alias: Holiday - Enable Christmas Lighting

  trigger:
    - platform: state
      entity_id: calendar.holidays_in_united_states
      to: 'on'
      for:
        hours: 9
        minutes: 0
        seconds: 0

  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: sensor.holidays_calendar
        state: 'Christmas Eve'
      - condition: state
        entity_id: sensor.holidays_calendar
        state: 'Christmas Day'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.holiday
        option: 'Christmas'

        ##########################################################
        ## Enable Halloween Lighting
        ##########################################################

- alias: Holiday - Enable Halloween Lighting

  trigger:
    - platform: state
      entity_id: calendar.holidays_in_united_states
      to: 'on'
      for:
        hours: 9
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: sensor.holidays_calendar
      state: 'Halloween'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.holiday
        option: 'Halloween'

        ##########################################################
        ## Enable St. Patuserones Day Lighting
        ##########################################################

- alias: Holiday - Enable St. Patuserones Day Lighting

  trigger:
    - platform: state
      entity_id: calendar.holidays_in_united_states
      to: 'on'
      for:
        hours: 9
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: sensor.holidays_calendar
      state: "St. Patuserones Day"

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.holiday
        option: "St. Patuserones Day"

        ##########################################################
        ## Enable Valentine's Day Lighting
        ##########################################################

- alias: Holiday - Enable Valentine's Day Lighting

  trigger:
    - platform: state
      entity_id: calendar.holidays_in_united_states
      to: 'on'
      for:
        hours: 9
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: sensor.holidays_calendar
      state: "Valentine's Day"

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.holiday
        option: "Valentine's Day"

        ##########################################################
        ## Enable Easter Lighting
        ##########################################################

- alias: Holiday - Enable Easter Lighting

  trigger:
    - platform: state
      entity_id: calendar.holidays_in_united_states
      to: 'on'
      for:
        hours: 9
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: sensor.holidays_calendar
      state: "Easter Sunday"

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.holiday
        option: 'Easter'

        ##########################################################
        ## Enable Thanksgiving Lighting
        ##########################################################

- alias: Holiday - Enable Thanksgiving Lighting

  trigger:
    - platform: state
      entity_id: calendar.holidays_in_united_states
      to: 'on'
      for:
        hours: 9
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: sensor.holidays_calendar
      state: "Thanksgiving Day"

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.holiday
        option: 'Thanksgiving'

        ##########################################################
        ## Enable Independence Day Lighting
        ##########################################################

- alias: Holiday - Enable Independence Day Lighting

  trigger:
    - platform: state
      entity_id: calendar.holidays_in_united_states
      to: 'on'
      for:
        hours: 9
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: sensor.holidays_calendar
      state: "Independence Day"

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.holiday
        option: 'Independence Day'

        ##########################################################
        ## Enable Memorial Day Lighting
        ##########################################################

- alias: Holiday - Enable Memorial Day Lighting

  trigger:
    - platform: state
      entity_id: calendar.holidays_in_united_states
      to: 'on'
      for:
        hours: 9
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: sensor.holidays_calendar
      state: "Memorial Day"

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.holiday
        option: 'Memorial Day'

        ##########################################################
        ## Enable Veterans Day Lighting
        ##########################################################

- alias: Holiday - Enable Veterans Day Lighting

  trigger:
    - platform: state
      entity_id: calendar.holidays_in_united_states
      to: 'on'
      for:
        hours: 9
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: sensor.holidays_calendar
      state: "Veterans Day"

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.holiday
        option: 'Veterans Day'

        ##########################################################
        ## Enable Labor Day Lighting
        ##########################################################

- alias: Holiday - Enable Labor Day Lighting

  trigger:
    - platform: state
      entity_id: calendar.holidays_in_united_states
      to: 'on'
      for:
        hours: 9
        minutes: 0
        seconds: 0

  condition:
    - condition: state
      entity_id: sensor.holidays_calendar
      state: "Labor Day"

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.holiday
        option: 'Labor Day'

        ##########################################################
        ## Christmas Lighting Interior
        ##########################################################

- alias: Holiday - Christmas Lighting Interior

  trigger:
    - platform: state
      entity_id: input_boolean.interior_holiday
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_select.holiday
      state: 'Christmas'

  action:
    - service: light.turn_on
      entity_id: light.master_strip
      data:
        effect: Christmas
        brightness: 255
        transition: 60

        ##########################################################
        ## Halloween Lighting Interior
        ##########################################################

- alias: Holiday - Halloween Lighting Interior

  trigger:
    - platform: state
      entity_id: input_boolean.interior_holiday
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_select.holiday
      state: 'Halloween'

  action:
    - service: light.turn_on
      entity_id: light.master_strip
      data:
        transition: 5
        brightness: 255
        # Dark Orange
        xy_color: [ 0.6164, 0.3645 ]

        ##########################################################
        ## St. Patuserones Day Lighting Interior
        ##########################################################

- alias: Holiday - St. Patuserones Day Lighting Interior

  trigger:
    - platform: state
      entity_id: input_boolean.interior_holiday
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_select.holiday
      state: "St. Patuserone's Day"

  action:
    - service: light.turn_on
      entity_id: light.master_strip
      data:
        transition: 5
        brightness: 255
        color_name: green

        ##########################################################
        ## Valentine's Day Lighting Interior
        ##########################################################

- alias: Holiday - Valentine's Day Lighting Interior

  trigger:
    - platform: state
      entity_id: input_boolean.interior_holiday
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_on_sunset
      state: 'off'
    - condition: state
      entity_id: input_select.holiday
      state: "Valentine's Day"

  action:
    - service: light.turn_on
      entity_id: light.master_strip
      data:
        transition: 5
        brightness: 255
        color_name: "hot pink"

        ##########################################################
        ## Easter Lighting Interior
        ##########################################################

- alias: Holiday - Easter Lighting Interior

  trigger:
    - platform: state
      entity_id: input_boolean.interior_holiday
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_select.holiday
      state: 'Easter'

  action:
    - service: light.turn_on
      entity_id: light.master_strip
      data:
        transition: 5
        brightness: 255
        color_name: indigo

        ##########################################################
        ## Thanksgiving Lighting Interior
        ##########################################################

- alias: Holiday - Thanksgiving Lighting Interior

  trigger:
    - platform: state
      entity_id: input_boolean.interior_holiday
      from: 'off'
      to: 'on'

  condition:
    - condition: state
      entity_id: input_select.holiday
      state: 'Thanksgiving'

  action:
    - service: light.turn_on
      entity_id: light.master_strip
      data:
        transition: 5
        brightness: 255
        # Orange
        xy_color: [ 0.5781, 0.3921 ]

        ##########################################################
        ## Independence / Memorial / Veterans / Labor Day Lighting Interior
        ##########################################################

- alias: Holiday - Independence / Memorial / Veterans / Labor Day Lighting Interior

  trigger:
    - platform: state
      entity_id: input_boolean.interior_holiday
      from: 'off'
      to: 'on'

  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.holiday
        state: 'Labor Day'
      - condition: state
        entity_id: input_select.holiday
        state: 'Memorial Day'
      - condition: state
        entity_id: input_select.holiday
        state: 'Independence Day'
      - condition: state
        entity_id: input_select.holiday
        state: 'Veterans Day'

  action:
    - service: light.turn_on
      entity_id: light.master_strip
      data:
        transition: 5
        brightness: 255
        color_name: blue

        ##########################################################
        ## Reset Holiday Lighting at 4a
        ##########################################################

- alias: Holiday - Reset Lighting at 4a

  trigger:
    - platform: time
      at: '04:00'

  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_select.holiday
        state: 'Halloween'
      - condition: state
        entity_id: input_select.holiday
        state: "St. Patuserone's Day"
      - condition: state
        entity_id: input_select.holiday
        state: 'Easter'
      - condition: state
        entity_id: input_select.holiday
        state: "Valentine's Day"
      - condition: state
        entity_id: input_select.holiday
        state: 'Thanksgiving'
      - condition: state
        entity_id: input_select.holiday
        state: 'Labor Day'
      - condition: state
        entity_id: input_select.holiday
        state: 'Memorial Day'
      - condition: state
        entity_id: input_select.holiday
        state: 'Independence Day'
      - condition: state
        entity_id: input_select.holiday
        state: 'Veterans Day'

  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.holiday
        option: "None"
