#################################################################
## Lighting Automations
#################################################################

        ##########################################################
        ## Exterior
        ##########################################################

- alias: lights exterior lights on 5min before sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:05:00"
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_on_sunset
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.exterior_lights
      data:
        brightness: 254

- alias: lights exterior lights dim at 9pm
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_dim_9pm
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.exterior_lights
      data:
        transition: 60
        brightness: 85

- alias: lights exterior lights off 30min after sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: "00:30:00"
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_off_sunrise
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: group.exterior_lights
      data:
        transition: 60

        ##########################################################
        ## Interior Media Center
        ##########################################################

- alias: lights interior media center reset after holiday lights
  trigger:
    - platform: state
      entity_id: input_boolean.interior_holiday
      from: 'on'
      to: 'off'
  action:
    - service: light.turn_on
      entity_id: group.media_center_lights
      data:
        transition: 5
        brightness: 35
        kelvin: 5000

        ##########################################################
        ## Interior Chalkboard Room
        ##########################################################

- alias: lights chalkboard room cactus light button
  trigger:
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001b76826
        click_type: single
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001b76826
        click_type: double
    - platform: event
      event_type: xiaomi_aqara.click
      event_data:
        entity_id: binary_sensor.switch_158d0001b76826
        click_type: long_click_press
  action:
    - service: homeassistant.toggle
      entity_id: switch.wemominicactus
