#################################################################
## Lighting Automations
#################################################################

        ##########################################################
        ## Exterior
        ##########################################################

- alias: Lights - Exterior lights on 5min before sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:05:00"
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_on_sunset
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.exterior_lights
      data:
        brightness: 254

- alias: Lights - Exterior lights dim at 9:00pm
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_dim_9pm
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.exterior_lights
      data:
        transition: 60
        brightness: 85

- alias: Lights - Exterior lights off 30min after sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: "00:30:00"
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_off_sunrise
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: group.exterior_lights
      data:
        transition: 60

        ##########################################################
        ## Interior Loft
        ##########################################################

- alias: Lights - Interior Loft Turn on 30% at Sunset if Home
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:00:30"
  condition:
    - condition: state
      entity_id: input_boolean.disable_loft_on_sunset
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
  action:
    - service: light.turn_on
      entity_id: group.loft_lights
      data:
        brightness: 75
        transition: 5

- alias: Lights - Interior Loft Turn off at 8:10PM
  trigger:
    - platform: time
      at: '20:10:00'
  condition:
    - condition: state
      entity_id: input_boolean.disable_loft_off_8pm
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: group.loft_lights
      data:
       transition: 60

        ##########################################################
        ## Interior Master
        ##########################################################

- alias: Lights - Interior Master Turn on at Sunset if Home
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:00:30"
  condition:
    - condition: state
      entity_id: input_boolean.disable_master_on_sunset
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
  action:
    - service: light.turn_on
      entity_id: light.master_strip
      data:
        transition: 5
        brightness: 255
        kelvin: 4500

- alias: Lights - Interior Master Turn off at 845PM
  trigger:
    - platform: time
      at: '20:45:00'
  condition:
    - condition: state
      entity_id: input_boolean.disable_master_off_845pm
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: light.master_strip
      data:
       transition: 300
