#################################################################
## Lighting Automations
#################################################################

        ##########################################################
        ## Exterior
        ##########################################################

- alias: Lights - Exterior lights on 5min before sunset
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:05:00"
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_on_sunset
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.exterior_lights
      data:
        brightness: 254

- alias: Lights - Exterior lights dim at 9:00pm
  trigger:
    - platform: time
      at: '21:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_dim_9pm
      state: 'off'
  action:
    - service: light.turn_on
      entity_id: group.exterior_lights
      data:
        transition: 60
        brightness: 85

- alias: Lights - Exterior lights off 30min after sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: "00:30:00"
  condition:
    - condition: state
      entity_id: input_boolean.disable_exterior_off_sunrise
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: group.exterior_lights
      data:
        transition: 60

        ##########################################################
        ## Interior Loft
        ##########################################################

- alias: Lights - Interior Loft Turn on 30% at Sunset if Home
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:00:30"
  condition:
    - condition: state
      entity_id: input_boolean.disable_loft_on_sunset
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
  action:
    - service: light.turn_on
      entity_id: group.loft_lights
      data:
        brightness: 75
        transition: 5

- alias: Lights - Interior Loft Turn off at 8:10PM
  trigger:
    - platform: time
      at: '20:10:00'
  condition:
    - condition: state
      entity_id: input_boolean.disable_loft_off_8pm
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: group.loft_lights
      data:
       transition: 60

        ##########################################################
        ## Interior Media Center
        ##########################################################

- alias: Lights - Interior Media Center Turn on at Sunset if Home
  trigger:
    - platform: sun
      event: sunset
      offset: "-00:00:30"
  condition:
    - condition: state
      entity_id: input_boolean.disable_media_center_on_sunset
      state: 'off'
    - condition: state
      entity_id: group.household
      state: 'home'
  action:
    - service: light.turn_on
      entity_id: group.media_center_lights
      data:
        transition: 5
        brightness: 20
        kelvin: 5000

- alias: Lights - Interior Media Center Turn off at 800PM
  trigger:
    - platform: time
      at: '20:00:00'
  condition:
    - condition: state
      entity_id: input_boolean.disable_media_center_off_800pm
      state: 'off'
  action:
    - service: light.turn_off
      entity_id: group.media_center_lights
      data:
       transition: 300

- alias: Lights - Interior Media Center Turn on if Motion detected after 8pm
  trigger:
    - platform: state
      entity_id: sensor.living_room_motion_detected
      from: 'False'
      to: 'True'
  condition:
    - condition: state
      entity_id: sensor.media_center
      state: 'PowerOff'
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: time
      after: '20:00:00'
      before: '05:00:00'
  action:
    - service: light.turn_on
      entity_id: group.media_center_lights
      data:
        transition: 5
        brightness: 100
        kelvin: 5000

- alias: Lights - Interior Media Center Turn off if Motion not detected after 8pm
  trigger:
    - platform: state
      entity_id: sensor.living_room_motion_detected
      from: 'True'
      to: 'False'
      for: '00:05:00'
  condition:
    - condition: time
      after: '20:00:00'
      before: '05:00:00'
  action:
    - service: light.turn_off
      entity_id: group.media_center_lights
