#################################################################
## Location Automations
#################################################################

        ##########################################################
        ## Set userone Away after 2 Min
        ##########################################################

- alias: Location - Set userone Away after 2 Mins
  trigger:
    - platform: state
      entity_id: device_tracker.useronedevice
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 2
        seconds: 0
  action:
    - service: homeassistant.turn_on
      entity_id:
        - input_boolean.userone_greeting
        - input_boolean.userone_away
        
        ##########################################################
        ## Set usetwo Away after 2 Min
        ##########################################################

- alias: Location - Set usetwo Away after 2 Mins
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'home'
      to: 'not_home'
      for:
        hours: 0
        minutes: 2
        seconds: 0
  action:
    - service: homeassistant.turn_on
      entity_id:
        - input_boolean.usertwo_greeting
        - input_boolean.usertwo_away

        ##########################################################
        ## Set userone Home after 10 Mins
        ##########################################################

- alias: Location - Set userone Home after 10 Mins
  trigger:
    - platform: state
      entity_id: device_tracker.useronedevice
      from: 'not_home'
      to: 'home'
      for:
        hours: 0
        minutes: 10
        seconds: 0
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.userone_away
        - input_boolean.userone_away_driving
        - input_boolean.userone_greeting  

        ##########################################################
        ## Set usetwo Home after 10 Mins
        ##########################################################

- alias: Location - Set usetwo Home after 10 Mins
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'not_home'
      to: 'home'
      for:
        hours: 0
        minutes: 10
        seconds: 0
  action:
    - service: homeassistant.turn_off
      entity_id:
        - input_boolean.usertwo_away
        - input_boolean.usertwo_away_driving
        - input_boolean.usertwo_greeting   

        ##########################################################
        ## Set userone Away Driving
        ##########################################################

- alias: Location - Set userone Away Driving
  trigger:
    - platform: state
      entity_id: device_tracker.useronedevice
      from: 'home'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.garage_occupancy
      state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.userone_away_driving 

        ##########################################################
        ## Set usetwo Away Driving
        ##########################################################

- alias: Location - Set usetwo Away Driving
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'home'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: input_boolean.garage_occupancy
      state: 'on'
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.usertwo_away_driving      

        ##########################################################
        ## Manually Set userone Away
        ##########################################################

- alias: Location - Manually Set userone Away
  trigger:
    - platform: state
      entity_id: input_boolean.manual_userone_away
      from: 'off'
      to: 'on'
  action:
    - service: device_tracker.see
      data:
        dev_id: useronedevice
        location_name: 'not_home'

        ##########################################################
        ## Reset Manually Set userone Away Switch
        ##########################################################

- alias: Location - Reset Manually Set userone Away
  trigger:
    - platform: state
      entity_id: input_boolean.manual_userone_away
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 30
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.manual_userone_away  

        ##########################################################
        ## Manually Set usetwo Away
        ##########################################################

- alias: Location - Manually Set usetwo Away
  trigger:
    - platform: state
      entity_id: input_boolean.manual_usertwo_away
      from: 'off'
      to: 'on'
  action:
    - service: device_tracker.see
      data:
        dev_id: usertwodevice
        location_name: 'not_home'

        ##########################################################
        ## Reset Manually Set usetwo Away Switch
        ##########################################################

- alias: Location - Reset Manually Set usetwo Away
  trigger:
    - platform: state
      entity_id: input_boolean.manual_usertwo_away
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 30
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.manual_usertwo_away   

        ##########################################################
        ## Manually Set userone Home
        ##########################################################

- alias: Location - Manually Set userone Home
  trigger:
    - platform: state
      entity_id: input_boolean.manual_userone_home
      from: 'off'
      to: 'on'
  action:
    - service: device_tracker.see
      data:
        dev_id: useronedevice
        location_name: 'home'

        ##########################################################
        ## Reset Manually Set userone Home Switch
        ##########################################################

- alias: Location - Reset userone Home
  trigger:
    - platform: state
      entity_id: input_boolean.manual_userone_home
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 30
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.manual_userone_home   

        ##########################################################
        ## Manually Set usetwo Home
        ##########################################################

- alias: Location - Manually Set usetwo Home
  trigger:
    - platform: state
      entity_id: input_boolean.manual_usertwo_home
      from: 'off'
      to: 'on'
  action:
    - service: device_tracker.see
      data:
        dev_id: usertwodevice
        location_name: 'home'

        ##########################################################
        ## Reset Manually Set usetwo Home Switch
        ##########################################################

- alias: Location - Reset usetwo Home
  trigger:
    - platform: state
      entity_id: input_boolean.manual_usertwo_home
      from: 'off'
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 30
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.manual_usertwo_home