#################################################################
## Audio Notification Automations
#################################################################

        ##########################################################
        ## Sonos - Notification Test
        ##########################################################

- alias: Notification Audio - Test
  trigger:
    - platform: state
      entity_id: input_boolean.test_audio_notification
      from: 'off'
      to: 'on'
  action:
    - service: media_player.sonos_snapshot
      data:
        with_group: yes
    - service: media_player.sonos_unjoin
      entity_id:
        - media_player.chalkboard_room
        - media_player.kitchen
        - media_player.loft
    - delay: '00:00:01'
    - service: media_player.sonos_join
      data:
        master: media_player.chalkboard_room
      entity_id:
        - media_player.chalkboard_room
        - media_player.kitchen
        - media_player.loft
    - service: media_player.volume_set
      entity_id:
        - media_player.chalkboard_room
        - media_player.kitchen
        - media_player.loft
      data:
        volume_level: '.6'
    - delay: '00:00:02'
    - service: tts.google_say
      data_template:
        entity_id:
        - media_player.chalkboard_room
        message: >
          {% set hour = now().strftime("%H") %}
          {% set weekday_full_name = now().strftime("%A") %}
          {% set month_full_name = now().strftime("%B") %}
          {% set day = now().strftime("%-d") %}
          {% set weekday = now().strftime("%w") %}
          {% if hour | int < 12 %}
          Good morning.
          {% elif hour | int < 18 %}
          Good afternoon.
          {% else %}
          Good evening.
          {% endif %}
          This is a test of the text to speech engine.
          Today is {{ weekday_full_name }} {{ month_full_name }} the
            {% if day | int == 1 or day | int == 21 or day | int == 31 %}
              {{ day }}st
            {% elif day | int == 2 or day | int == 22 %}
              {{ day }}nd
            {% elif day | int == 3 or day | int == 23 %}
              {{ day }}rd
            {% else %}
              {{ day }}th
            {% endif %}.
          It's currently {{states.sensor.dark_sky_summary.state}} and {{states.sensor.dark_sky_temperature.state|round}} degrees in REDACTED. Today will be {{states.sensor.dark_sky_hourly_summary.state|replace(".", "")}}, with a high of {{states.sensor.dark_sky_daily_high_temperature.state|round}} degrees.
          End of test.
    - delay: '00:00:20'
    - service: media_player.sonos_restore
      data_template:
        with_group: yes
    - service: homeassistant.turn_off
      entity_id: input_boolean.test_audio_notification

        ##########################################################
        ## Sonos - Good morning - Weekday
        ##########################################################

- alias: Notification Audio - Good morning weekday
  trigger:
    - platform: time
      at: '06:45:00'
  condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: state
          entity_id: group.household
          state: 'home'
        - condition: state
          entity_id: input_boolean.disable_voice_greeting
          state: 'off'
  action:
    - delay: '00:00:30'
    - service: script.turn_on
      entity_id: script.good_morning

        ##########################################################
        ## Sonos - Good morning - Weekend
        ##########################################################

- alias: Notification Audio - Good morning weekend
  trigger:
    - platform: time
      at: '08:20:00'
  condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - sat
            - sun
        - condition: state
          entity_id: group.household
          state: 'home'
        - condition: state
          entity_id: input_boolean.disable_voice_greeting
          state: 'off'
  action:
    - delay: '00:00:30'
    - service: script.turn_on
      entity_id: script.good_morning

        ##########################################################
        ## Sonos - Welcome Home userone
        ##########################################################

- alias: Notification Audio - Welcome Home userone
  trigger:
    - platform: state
      entity_id: device_tracker.useronedevice
      from: 'not_home'
      to: 'home'
      for: '00:02:00'
  condition:
    - condition: time
      after: '07:30'
      before: '19:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
    - condition: state
      entity_id: input_boolean.userone_greeting
      state: 'on'
  action:
    - delay: '00:00:10'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft'
          volume: '.5'
          what: 'Welcome home userone.'
    - delay: '00:00:10'
    - service: homeassistant.turn_off
      entity_id: input_boolean.userone_greeting

        ##########################################################
        ## Sonos - Welcome Home usertwo
        ##########################################################

- alias: Notification Audio - Welcome Home usertwo
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'not_home'
      to: 'home'
      for: '00:02:30'
  condition:
    - condition: time
      after: '08:00'
      before: '19:00'
    - condition: state
      entity_id: input_boolean.usertwo_greeting
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:10'
    - service: script.turn_on
      entity_id: script.say
      data_template:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft'
          volume: '.5'
          # {% set person = entity.split('.')[1].split('_')[0]|replace('REDACTED','usertwo') %}
          what: '{{ ["Welcome home usertwo.","It is great to see you usertwo, I hope you had a great day!","You look amazing usertwo, glad to see you are home.","usertwo, I missed you so much, glad you are home."] | random }}'
    - delay: '00:00:10'
    - service: homeassistant.turn_off
      entity_id: input_boolean.usertwo_greeting

        ##########################################################
        ## Sonos - usertwo has arrived at work
        ##########################################################

- alias: Notification Audio - usertwo arrived at work
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'not_home'
      to: 'Work'
  condition:
    - condition: state
      entity_id: device_tracker.useronedevice
      state: 'home'
    - condition: time
      after: '07:00'
      before: '09:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:05'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft'
          volume: '.6'
          what: 'usertwo has arrived at work.'

        ##########################################################
        ## Sonos - usertwo Left Work to REDACTED
        ##########################################################

- alias: Notification Audio - usertwo Left Work
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'Work'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.useronedevice
      state: 'home'
    - condition: time
      after: '15:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:10'
    - service: script.turn_on
      entity_id: script.say
      data_template:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft'
          volume: '.6'
          what: "usertwo has left work and will arrive at REDACTED REDACTED in about {{states('sensor.usertwo_to_REDACTED')}} minutes."

        ##########################################################
        ## Sonos - usertwo Arrived REDACTED
        ##########################################################

- alias: Notification Audio - usertwo Arrived REDACTED
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'not_home'
      to: 'REDACTED'
  condition:
    - condition: state
      entity_id: device_tracker.useronedevice
      state: 'home'
    - condition: time
      after: '13:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:05'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft'
          volume: '.6'
          what: 'usertwo has arrived at REDACTED REDACTED.'

        ##########################################################
        ## Sonos - usertwo Left REDACTED to REDACTED
        ##########################################################

- alias: Notification Audio - usertwo Left REDACTED to REDACTED
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'REDACTED'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.useronedevice
      state: 'home'
    - condition: time
      after: '13:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:10'
    - service: script.turn_on
      entity_id: script.say
      data_template:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft'
          volume: '.6'
          what: "usertwo has left REDACTED REDACTED and will arrive at REDACTED REDACTED in about {{states('sensor.usertwo_to_REDACTED')}} minutes."

        ##########################################################
        ## Sonos - usertwo Arrived REDACTED
        ##########################################################

- alias: Notification Audio - usertwo Arrived REDACTED
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'not_home'
      to: 'REDACTED'
  condition:
    - condition: state
      entity_id: device_tracker.useronedevice
      state: 'home'
    - condition: time
      after: '13:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:05'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft'
          volume: '.6'
          what: 'usertwo has arrived at REDACTED school.'

        ##########################################################
        ## Sonos - usertwo Left REDACTED to Home
        ##########################################################

- alias: Notification Audio - REDACTED to Home
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'REDACTED'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.useronedevice
      state: 'home'
    - condition: time
      after: '13:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:10'
    - service: script.turn_on
      entity_id: script.say
      data_template:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft'
          volume: '.6'
          what: "usertwo has left REDACTED REDACTED and will arrive home in about {{states('sensor.usertwo_to_home')}} minutes."

        ##########################################################
        ## Sonos - Garage door has been open for 30min
        ##########################################################

- alias: Notification Audio - Garage open for 30min
  trigger:
    - platform: state
      entity_id: binary_sensor.ecolink_tilt_big_garage_sensor
      to: 'on'
      for:
        minutes: 30
  condition:
    - condition: state
      entity_id: group.household
      state: 'home'
    - condition: time
      after: '07:00'
      before: '21:00'
    - condition: state
      entity_id: binary_sensor.garage_occupancy_on
      state: 'off'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:05'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.chalkboard_room'
          where: 'media_player.chalkboard_room, media_player.kitchen, media_player.loft'
          volume: '.6'
          what: 'The garage has been open for 30 minutes.'
