#################################################################
## Audio Notification Automations
#################################################################

        ##########################################################
        ## Sonos - Good morning - Weekday
        ##########################################################

- alias: Notification Audio - Good morning weekday
  trigger:
    - platform: time
      at: '06:45:00'
  condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: state
          entity_id: group.household
          state: 'home'
        - condition: state
          entity_id: input_boolean.disable_voice_greeting
          state: 'off'
  action:
    - delay: '00:00:30'
    - service: script.turn_on
      entity_id: script.good_morning

        ##########################################################
        ## Sonos - Good morning - Weekend
        ##########################################################

- alias: Notification Audio - Good morning weekend
  trigger:
    - platform: time
      at: '08:20:00'
  condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - sat
            - sun
        - condition: state
          entity_id: group.household
          state: 'home'
        - condition: state
          entity_id: input_boolean.disable_voice_greeting
          state: 'off'
  action:
    - delay: '00:00:30'
    - service: script.turn_on
      entity_id: script.good_morning

        ##########################################################
        ## Sonos - Turn on exterior lights
        ##########################################################

#- alias: Notification Audio - Turn on exterior lights
#  trigger:
#    - platform: sun
#      event: sunset
#      offset: "-00:05:00"
#  condition:
#    - condition: state
#      entity_id: input_boolean.disable_voice_greeting
#      state: 'off'
#    - condition: state
#      entity_id: group.household
#      state: 'home'
#  action:
#    - delay: '00:00:30'
#    - service: script.turn_on
#      entity_id: script.dark_outside

        ##########################################################
        ## Sonos - Welcome Home userone
        ##########################################################

- alias: Notification Audio - Welcome Home userone
  trigger:
    - platform: state
      entity_id: device_tracker.useronedevice
      from: 'not_home'
      to: 'home'
  condition:
    - condition: time
      after: '08:00'
      before: '19:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
    - condition: state
      entity_id: input_boolean.userone_greeting
      state: 'on'
  action:
    - delay: '00:00:30'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.kitchen, media_player.chalkboard_room, media_player.loft'
          volume: '.5'
          what: 'Welcome home userone.'
    - delay: '00:00:10'
    - service: homeassistant.turn_off
      entity_id: input_boolean.userone_greeting

        ##########################################################
        ## Sonos - Welcome Home usetwo
        ##########################################################

- alias: Notification Audio - Welcome Home usetwo
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'not_home'
      to: 'home'
  condition:
    - condition: time
      after: '08:00'
      before: '19:00'
    - condition: state
      entity_id: input_boolean.usertwo_greeting
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:01:30'
    - service: script.turn_on
      entity_id: script.say
      data_template:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.kitchen, media_player.chalkboard_room, media_player.loft'
          volume: '.5'
          what: '{{ ["Welcome home usetwo.","It is great to see you usetwo, I hope you had a great day!","You look amazing usetwo, glad to see you are home.","usetwo, I missed you so much, glad you are home."] | random }}'
    - delay: '00:00:10'
    - service: homeassistant.turn_off
      entity_id: input_boolean.usertwo_greeting

        ##########################################################
        ## Sonos - usetwo has arrived at work
        ##########################################################

- alias: Notification Audio - usetwo arrived at work
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'not_home'
      to: 'Work'
  condition:
    - condition: state
      entity_id: device_tracker.useronedevice
      state: 'home'
    - condition: time
      after: '07:00'
      before: '09:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:05'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.kitchen, media_player.chalkboard_room, media_player.loft'
          volume: '.6'
          what: 'usetwo has arrived at work.'

        ##########################################################
        ## Sonos - usetwo Left Work to REDACTED
        ##########################################################

- alias: Notification Audio - usetwo Left Work
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'Work'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.useronedevice
      state: 'home'
    - condition: time
      after: '15:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:10'
    - service: script.turn_on
      entity_id: script.say
      data_template:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.kitchen, media_player.chalkboard_room, media_player.loft'
          volume: '.6'
          what: "usetwo has left work and will arrive at REDACTED REDACTED in about {{states('sensor.usertwo_to_REDACTED')}} minutes."

        ##########################################################
        ## Sonos - usetwo Arrived REDACTED
        ##########################################################

- alias: Notification Audio - usetwo Arrived REDACTED
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'not_home'
      to: 'REDACTED'
  condition:
    - condition: state
      entity_id: device_tracker.useronedevice
      state: 'home'
    - condition: time
      after: '13:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:05'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.kitchen, media_player.chalkboard_room, media_player.loft'
          volume: '.6'
          what: 'usetwo has arrived at REDACTED REDACTED.'

        ##########################################################
        ## Sonos - usetwo Left REDACTED to REDACTED
        ##########################################################

- alias: Notification Audio - usetwo Left REDACTED to REDACTED
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'REDACTED'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.useronedevice
      state: 'home'
    - condition: time
      after: '13:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:10'
    - service: script.turn_on
      entity_id: script.say
      data_template:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.kitchen, media_player.chalkboard_room, media_player.loft'
          volume: '.6'
          what: "usetwo has left REDACTED REDACTED and will arrive at REDACTED REDACTED in about {{states('sensor.usertwo_to_REDACTED')}} minutes."

        ##########################################################
        ## Sonos - usetwo Arrived REDACTED
        ##########################################################

- alias: Notification Audio - usetwo Arrived REDACTED
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'not_home'
      to: 'REDACTED'
  condition:
    - condition: state
      entity_id: device_tracker.useronedevice
      state: 'home'
    - condition: time
      after: '13:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:05'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.kitchen, media_player.chalkboard_room, media_player.loft'
          volume: '.6'
          what: 'usetwo has arrived at REDACTED school.'

        ##########################################################
        ## Sonos - usetwo Left REDACTED to Home
        ##########################################################

- alias: Notification Audio - REDACTED to Home
  trigger:
    - platform: state
      entity_id: device_tracker.usertwodevice
      from: 'REDACTED'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.useronedevice
      state: 'home'
    - condition: time
      after: '13:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:10'
    - service: script.turn_on
      entity_id: script.say
      data_template:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.kitchen, media_player.chalkboard_room, media_player.loft'
          volume: '.6'
          what: "usetwo has left REDACTED REDACTED and will arrive home in about {{states('sensor.usertwo_to_home')}} minutes."
