#################################################################
## Audio Notification Automations
#################################################################

        ##########################################################
        ## Sonos - Good morning - Weekday
        ##########################################################

- alias: Notification Audio - Good morning weekday
  trigger:
    - platform: time
      at: '06:45:00'
  condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - mon
            - tue
            - wed
            - thu
            - fri
        - condition: state
          entity_id: group.household
          state: 'home'
        - condition: state
          entity_id: input_boolean.disable_voice_greeting
          state: 'off'
  action:
    - delay: '00:00:30'
    - service: script.turn_on
      entity_id: script.good_morning

        ##########################################################
        ## Sonos - Good morning - Weekend
        ##########################################################

- alias: Notification Audio - Good morning weekend
  trigger:
    - platform: time
      at: '08:20:00'
  condition:
      condition: and
      conditions:
        - condition: time
          weekday:
            - sat
            - sun
        - condition: state
          entity_id: group.household
          state: 'home'
        - condition: state
          entity_id: input_boolean.disable_voice_greeting
          state: 'off'
  action:
    - delay: '00:00:30'
    - service: script.turn_on
      entity_id: script.good_morning

        ##########################################################
        ## Sonos - Turn on exterior lights
        ##########################################################

#- alias: Notification Audio - Turn on exterior lights
#  trigger:
#    - platform: sun
#      event: sunset
#      offset: "-00:05:00"
#  condition:
#    - condition: state
#      entity_id: input_boolean.disable_voice_greeting
#      state: 'off'
#    - condition: state
#      entity_id: group.household
#      state: 'home'
#  action:
#    - delay: '00:00:30'
#    - service: script.turn_on
#      entity_id: script.dark_outside 

        ##########################################################
        ## Sonos - Welcome Home USER1
        ##########################################################

- alias: Notification Audio - Welcome Home USER1
  trigger:
    - platform: state
      entity_id: device_tracker.USER1DEVICE
      from: 'not_home'
      to: 'home'
  condition:
    - condition: time
      after: '08:00'
      before: '19:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
    - condition: state
      entity_id: input_boolean.USER1_greeting
      state: 'on'
  action:
    - delay: '00:00:30'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.kitchen, media_player.chalkboard_room, media_player.loft'
          volume: '.5'
          what: 'Welcome home USER1.'
    - delay: '00:01:00'
    - service: homeassistant.turn_off
      entity_id: input_boolean.USER1_greeting

        ##########################################################
        ## Sonos - Welcome Home USER2
        ##########################################################

- alias: Notification Audio - Welcome Home USER2
  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'not_home'
      to: 'home'
  condition:
    - condition: time
      after: '08:00'
      before: '19:00'
    - condition: state
      entity_id: input_boolean.USER2_greeting
      state: 'on'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:01:30'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.kitchen, media_player.chalkboard_room, media_player.loft'
          volume: '.5'
          what: 'Welcome home USER2.'
    - delay: '00:01:00'
    - service: homeassistant.turn_off
      entity_id: input_boolean.USER2_greeting

        ##########################################################
        ## Sonos - USER2 has arrived at work
        ##########################################################

- alias: Notification Audio - USER2 arrived at work
  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'not_home'
      to: 'Work'
  condition:
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'home'
    - condition: time
      after: '07:00'
      before: '09:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:30'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.kitchen, media_player.chalkboard_room, media_player.loft'
          volume: '.6'
          what: 'USER2 has arrived at work.'

        ##########################################################
        ## Sonos - USER2 Left Work to REDACTED
        ##########################################################

- alias: Notification Audio - USER2 Left Work
  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'Work'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'home'
    - condition: time
      after: '15:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - service: media_player.sonos_snapshot
      data:
        with_group: yes
    - delay: '00:00:03'
    - service: media_player.sonos_unjoin
      entity_id:
        - media_player.kitchen
        - media_player.chalkboard_room
        - media_player.loft
    - delay: '00:00:01'
    - service: media_player.sonos_join
      data:
        master: media_player.kitchen
      entity_id:
        - media_player.kitchen
        - media_player.chalkboard_room
        - media_player.loft
    - delay: '00:00:01'
    - service: media_player.volume_set
      entity_id:
        - media_player.kitchen
        - media_player.chalkboard_room
        - media_player.loft
      data:
        volume_level: '.6'
    - delay: '00:00:02'
    - service: tts.google_say
      data_template:
        entity_id:
          - media_player.kitchen
          - media_player.chalkboard_room
          - media_player.loft
        message: "USER2 has left work and will arrive at REDACTED REDACTED in about {{states('sensor.USER2_to_REDACTED')}} minutes"
    - delay: '00:00:25'
    - service: media_player.sonos_restore
      data:
        with_group: yes

        ##########################################################
        ## Sonos - USER2 Arrived REDACTED
        ##########################################################

- alias: Notification Audio - USER2 Arrived REDACTED
  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'not_home'
      to: 'REDACTED'
  condition:
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'home'
    - condition: time
      after: '13:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:30'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.kitchen, media_player.chalkboard_room, media_player.loft'
          volume: '.6'
          what: 'USER2 has arrived at REDACTED REDACTED.'

        ##########################################################
        ## Sonos - USER2 Left REDACTED to REDACTED
        ##########################################################

- alias: Notification Audio - USER2 Left REDACTED to REDACTED
  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'REDACTED'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'home'
    - condition: time
      after: '13:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - service: media_player.sonos_snapshot
      data:
        with_group: yes
    - delay: '00:00:03'
    - service: media_player.sonos_unjoin
      entity_id:
        - media_player.kitchen
        - media_player.chalkboard_room
        - media_player.loft
    - delay: '00:00:01'
    - service: media_player.sonos_join
      data:
        master: media_player.kitchen
      entity_id:
        - media_player.kitchen
        - media_player.chalkboard_room
        - media_player.loft
    - delay: '00:00:01'
    - service: media_player.volume_set
      entity_id:
        - media_player.kitchen
        - media_player.chalkboard_room
        - media_player.loft
      data:
        volume_level: '.6'
    - delay: '00:00:02'
    - service: tts.google_say
      data_template:
        entity_id:
          - media_player.kitchen
          - media_player.chalkboard_room
          - media_player.loft
        message: "USER2 has left REDACTED REDACTED and will arrive at REDACTED REDACTED in about {{states('sensor.USER2_to_REDACTED')}} minutes"
    - delay: '00:00:25'
    - service: media_player.sonos_restore
      data:
        with_group: yes

        ##########################################################
        ## Sonos - USER2 Arrived REDACTED
        ##########################################################

- alias: Notification Audio - USER2 Arrived REDACTED
  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'not_home'
      to: 'REDACTED'
  condition:
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'home'
    - condition: time
      after: '13:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - delay: '00:00:30'
    - service: script.turn_on
      entity_id: script.say
      data:
        variables:
          master: 'media_player.kitchen'
          where: 'media_player.kitchen, media_player.chalkboard_room, media_player.loft'
          volume: '.6'
          what: 'USER2 has arrived at REDACTED school.'

        ##########################################################
        ## Sonos - USER2 Left REDACTED to Home
        ##########################################################

- alias: Notification Audio - REDACTED to Home
  trigger:
    - platform: state
      entity_id: device_tracker.USER2DEVICE
      from: 'REDACTED'
      to: 'not_home'
  condition:
    - condition: state
      entity_id: device_tracker.USER1DEVICE
      state: 'home'
    - condition: time
      after: '13:00'
      before: '18:00'
    - condition: state
      entity_id: input_boolean.disable_voice_greeting
      state: 'off'
  action:
    - service: media_player.sonos_snapshot
      data:
        with_group: yes
    - delay: '00:00:03'
    - service: media_player.sonos_unjoin
      entity_id:
        - media_player.kitchen
        - media_player.chalkboard_room
        - media_player.loft
    - delay: '00:00:01'
    - service: media_player.sonos_join
      data:
        master: media_player.kitchen
      entity_id:
        - media_player.kitchen
        - media_player.chalkboard_room
        - media_player.loft
    - delay: '00:00:01'
    - service: media_player.volume_set
      entity_id:
        - media_player.kitchen
        - media_player.chalkboard_room
        - media_player.loft
      data:
        volume_level: '.6'
    - delay: '00:00:02'
    - service: tts.google_say
      data_template:
        entity_id:
          - media_player.kitchen
          - media_player.chalkboard_room
          - media_player.loft
        message: "USER2 has left REDACTED REDACTED and will arrive home in about {{states('sensor.USER2_to_home')}} minutes"
    - delay: '00:00:25'
    - service: media_player.sonos_restore
      data:
        with_group: yes
